Fix a couple of misleading terms
riscv-non-isa/riscv-ap-tee-io pull request #65
Opened 2024-01-21 19:50 UTC by sameo

* non-confidential host software is better qualified as the host supervisor domain manager
* A RoT does not have to be 100% HW

2024-01-21 19:51 UTC, sameo commented
cc @steven-bellock

2024-01-21 23:28 UTC, steven-bellock requested changes
- https://github.com/riscv-non-isa/riscv-ap-tee-io/blob/main/specification/04-requirements.adoc 
- https://github.com/riscv-non-isa/riscv-ap-tee-io/blob/main/specification/07-theory_operations.adoc

has multiple instances of `HROT` / `Hardware Root-of-Trust`.

2024-01-22 07:28 UTC, sameo commented
> * https://github.com/riscv-non-isa/riscv-ap-tee-io/blob/main/specification/04-requirements.adoc
> 
>     * https://github.com/riscv-non-isa/riscv-ap-tee-io/blob/main/specification/07-theory_operations.adoc
> 
> 
> has multiple instances of `HROT` / `Hardware Root-of-Trust`.

Fixed now, thanks.

2024-01-22 15:42 UTC, steven-bellock approved these changes

2024-01-23 06:44 UTC, merged